language: rust
sudo: false
matrix:
  include:
    - rust: stable
      env:
       - NAME="stable"
       - FEATURES=''
    - rust: nightly
      env:
       - NAME="nightly"
       - FEATURES=''
    - rust: stable
      env:
       - NAME="stable,data"
       - FEATURES='data'
    - rust: nightly
      env:
       - NAME="nightly,data"
       - FEATURES='data'
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")
