[package]
name = "pcap-parser"
version = "0.4.0"
description = "Parser for the PCAP/PCAPNG format"
license = "MIT/Apache-2.0"
keywords = ["pcap","pcapng","parser","nom"]
homepage = "https://github.com/rusticata/pcap-parser"
repository = "https://github.com/rusticata/pcap-parser.git"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

readme = "README.md"
categories = ["parsing"]

include = [
  "LICENSE-*",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[features]
default = []

# include parsers for data (depending on linktype)
data = []

[dependencies]
nom = "4.0"
cookie-factory = "0.2"
byteorder = "1"
rusticata-macros = "1.1"

[badges]
travis-ci = { repository = "rusticata/pcap-parser" }
